apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tasker-alerts
  namespace: monitoring
spec:
  groups:
    - name: tasker
      rules:
        - alert: HighErrorRate
          expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) > 0.1
          for: 5m
          labels:
            severity: critical
          annotations:
            description: "Error rate is above 10% for 5 minutes"
