apiVersion: v1
kind: ConfigMap
metadata:
  name: tasker-config
  namespace: { { .Release.Namespace } }
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Values.database.host }}:5432/{{ .Values.database.name }}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
