apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasker-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ include "tasker-app.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
      flyway:
        url: jdbc:postgresql://{{ include "tasker-app.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
        user: ${DB_USER}
        password: ${DB_PASSWORD}
        baseline-on-migrate: true
        enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
    logging:
      level:
        org.springframework.jdbc: DEBUG
        org.flywaydb: DEBUG
        com.zaxxer.hikari: DEBUG