apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasker-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ include "tasker-app.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
    logging:
      level:
        root: INFO
        by.web.tasker_app: DEBUG
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file.name: /dev/null
  
  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
      <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

      <root level="INFO">
        <appender-ref ref="CONSOLE"/>
      </root>
      
      <logger name="by.web.tasker_app" level="DEBUG"/>
    </configuration>
