apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasker-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ include "tasker-app.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
