apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasker-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
      flyway:
        url: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
        user: ${DB_USER}
        password: ${DB_PASSWORD}
        baseline-on-migrate: true
        enabled: true
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: validate
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        show-sql: true
      autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
    logging:
      level:
        org.springframework.jdbc: DEBUG
        org.flywaydb: DEBUG
        com.zaxxer.hikari: DEBUG
        org.hibernate: DEBUG
        org.hibernate.SQL: DEBUG