apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasker-postgresql-pvc
  namespace: tasker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
