apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tasker-app.fullname" . }}
  labels: {{- include "tasker-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
