{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tasker-app.fullname" . }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "tasker-app.labels" . | nindent 4 }}
    release: prometheus
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | default "10s" }}
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: '(jvm|process|hikaricp|http_server|tomcat|system|logback|jdbc|application_started|application_ready|tasker_.*)'
          action: keep
  namespaceSelector:
    matchNames:
      - tasker
  selector:
    matchLabels:
      {{- include "tasker-app.selectorLabels" . | nindent 6 }}
{{- end }} 