apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasker-app.fullname" . }}
  labels: { { - include "tasker-app.labels" . | nindent 4 } }
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "tasker-app.selectorLabels" . | nindent 4 } }
