{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tasker-app.fullname" . }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  labels:
    {{- include "tasker-app.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      metricRelabelings:
        - sourceLabels: [ __name__ ]
          regex: (jvm_memory_used_bytes|process_cpu_usage|http_server_requests_seconds_count|system_cpu_usage|jvm_gc_pause_seconds_count|jvm_memory_committed_bytes|jvm_threads_live|hikaricp_connections_active|hikaricp_connections_usage|tasker_tasks_total|tasker_tasks_completed_total)
          action: keep
  selector:
    matchLabels:
      {{- include "tasker-app.selectorLabels" . | nindent 6 }}
{{- end }} 