apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tasker-alerts
  namespace: monitoring
  labels:
    app: tasker
    release: prometheus
spec:
  groups:
    - name: tasker.rules
      rules:
        - alert: TaskerHighCPUUsage
          expr: process_cpu_usage{job="tasker-app"} > 0.8
          for: 5m
          labels:
            severity: warning
            team: backend
          annotations:
            summary: "Высокая нагрузка на CPU в Tasker"
            description: "Tasker использует более 80% CPU в течение 5 минут"
            runbook_url: "https://github.com/Alex-AGD/tasker-infra/wiki/CPU-Troubleshooting"

        - alert: TaskerHighMemoryUsage
          expr: sum(jvm_memory_used_bytes{area="heap",job="tasker-app"}) / sum(jvm_memory_max_bytes{area="heap",job="tasker-app"}) > 0.9
          for: 5m
          labels:
            severity: warning
            team: backend
          annotations:
            summary: "Высокое использование памяти в Tasker"
            description: "Tasker использует более 90% памяти в течение 5 минут"
            runbook_url: "https://github.com/Alex-AGD/tasker-infra/wiki/Memory-Troubleshooting"

        - alert: TaskerDatabaseConnectionsExhausted
          expr: hikaricp_connections_active / hikaricp_connections_max > 0.8
          for: 2m
          labels:
            severity: critical
            team: database
          annotations:
            summary: "Исчерпываются соединения с БД"
            description: "Tasker использует более 80% доступных соединений с базой данных"
            runbook_url: "https://github.com/Alex-AGD/tasker-infra/wiki/Database-Troubleshooting"

        - alert: TaskerHighErrorRate
          expr: sum(rate(http_server_requests_seconds_count{status=~"5..",job="tasker-app"}[5m])) / sum(rate(http_server_requests_seconds_count{job="tasker-app"}[5m])) > 0.05
          for: 2m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "Высокий процент ошибок в Tasker"
            description: "Более 5% запросов заканчиваются ошибкой 5xx"
            runbook_url: "https://github.com/Alex-AGD/tasker-infra/wiki/Error-Troubleshooting"

        - alert: TaskerSlowResponses
          expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job="tasker-app"}[5m])) by (le, method, uri)) > 2
          for: 5m
          labels:
            severity: warning
            team: backend
          annotations:
            summary: "Медленные ответы в Tasker"
            description: "95-й процентиль времени ответа превышает 2 секунды"
            runbook_url: "https://github.com/Alex-AGD/tasker-infra/wiki/Performance-Troubleshooting"

        - alert: PostgreSQLHighCPU
          expr: rate(process_cpu_seconds_total{job="postgresql"}[5m]) > 0.8
          for: 5m
          labels:
            severity: warning
            team: database
          annotations:
            summary: "Высокая нагрузка на CPU в PostgreSQL"
            description: "PostgreSQL использует более 80% CPU в течение 5 минут"
            runbook_url: "https://github.com/Alex-AGD/tasker-infra/wiki/Database-CPU-Troubleshooting"
