apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasker-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://alex-agd.github.io/tasker-infra/
    path: monitoring
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
