apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alex-AGD/tasker-infra
    path: helm/tasker
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tasker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 1.5
        maxDuration: 1m
