apiVersion: v2
name: tasker-app
description: Helm chart для приложения Tasker
type: application
version: 0.1.4
appVersion: "1.0.0"
icon: https://helm.sh/img/helm.svg
maintainers:
  - name: "AlexAGD"
    email: "aliaksei.dalhapolau@gmail.com"
dependencies:
  - name: postgresql
    version: "12.8.2"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
